# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufobalapp', '0031_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('normal', 'běžný'), ('penalty', 'penalta'), ('shootout', 'penaltový rozstřel')], default='normal', max_length=20, verbose_name='druh'),
        ),
    ]
