# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-07 14:11
from __future__ import unicode_literals

import re

from django.db import migrations, models

from ufobalapp.models import Tournament


def fill_category_and_location(apps, schema_editor):
    for tournament in apps.get_model("ufobalapp", "Tournament").objects.all():
        name = tournament.name
        result = re.search(r'\((.*)\)', name)
        if result:
            place = result.group(1)
        else:
            place = None
        print(name, '->', place)

        if name.startswith('Brno'):
            tournament.category = Tournament.BRNO
            tournament.location = place if place else 'Brno'
            tournament.save()
            continue

        if name.startswith('Nížkov'):
            tournament.category = Tournament.NIZKOV
            tournament.location = place if place else 'Nížkov'
            tournament.save()
            continue

        if name.startswith('Losovaná Hala'):
            tournament.category = Tournament.OTHER
            tournament.location = place
            tournament.save()
            continue

        if name.startswith('Hala'):
            tournament.category = Tournament.HALA
            tournament.location = place
            tournament.save()
            continue

        assert False

class Migration(migrations.Migration):

    dependencies = [
        ('ufobalapp', '0034_tournament_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('brno', 'Brno'), ('nizkov', 'Nížkov'), ('hala', 'Hala'), ('other', 'Další'), ('liga', 'Liga'), ('trening', 'Tréning')], max_length=15, null=True, verbose_name='kategorie'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lokace'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Název'),
        ),
        migrations.RunPython(fill_category_and_location, lambda x, y: None),
    ]
