# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models


def close_old_tournaments(apps, schema_editor):
    apps.get_model("ufobalapp", "Tournament").objects.all().update(closed_edit=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ufobalapp', '0035_auto_20210207_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='closed_edit',
            field=models.BooleanField(default=False, verbose_name='Uzavřená editace'),
        ),
        migrations.RunPython(close_old_tournaments, lambda x, y: None),
    ]
