# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2022-03-19 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufobalapp', '0037_auto_20210306_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamontournament',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Čas registrace'),
        ),
    ]
