# Generated by Django 4.2.1 on 2026-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufobalapp', '0038_teamontournament_registration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_from',
            field=models.DateTimeField(blank=True, help_text='Kdy se turnaj vypustí. Dokud tento čas nenastane, přihlašování je zavřené. Prázdné znamená, že přihlašování je otevřené hned.', null=True, verbose_name='Přihlašování od'),
        ),
    ]
